// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA4WfP_haliZYDftPf0i3qfPtXPwosDCw',
    appId: '1:671024400454:web:c56bb77294425e220f2247',
    messagingSenderId: '671024400454',
    projectId: 'rest-diary-c01f6',
    authDomain: 'rest-diary-c01f6.firebaseapp.com',
    storageBucket: 'rest-diary-c01f6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAECnn8Y1Z7LPEg4Y6E6PO2DL0DwxgtVZc',
    appId: '1:671024400454:android:609405f8f2ac761c0f2247',
    messagingSenderId: '671024400454',
    projectId: 'rest-diary-c01f6',
    storageBucket: 'rest-diary-c01f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJpMQnKvKfjHnbscI41DtP8jvZJTUWNzA',
    appId: '1:671024400454:ios:75bb9e298a00685f0f2247',
    messagingSenderId: '671024400454',
    projectId: 'rest-diary-c01f6',
    storageBucket: 'rest-diary-c01f6.appspot.com',
    iosBundleId: 'com.example.restApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJpMQnKvKfjHnbscI41DtP8jvZJTUWNzA',
    appId: '1:671024400454:ios:73248263e89fe84c0f2247',
    messagingSenderId: '671024400454',
    projectId: 'rest-diary-c01f6',
    storageBucket: 'rest-diary-c01f6.appspot.com',
    iosClientId: '671024400454-mi2anjamv0fn6luul9p4dmpbih7g3plk.apps.googleusercontent.com',
    iosBundleId: 'com.example.restApp.RunnerTests',
  );
}
